### ISSUE TITLE
<dockerhost>

### ISSUE THREAD

**Issue by mallutester1** [sakaicontrib/docker-sakai-builder#3]
I appreciate you building this.

But I tried to do with the docker folder in the sakai official repo. 
I go in the deploy folder and do the asked steps. 

Do you know what they mean by http://  <  dddockerhost>:8080 there so that I can see sakai web interface loaded? I am unable to get the ip

**Comment by jonespm** [comment]
Sorry, I didn't write the scripts in the docker directory in the official repo. That uses docker swarm to set up the instance, I'm just building and starting the containers individually. I've never actually started that up. You could try to contact the [Sakai developer list ](https://groups.google.com/a/apereo.org/g/sakai-dev) but I'm not sure who else would know.
