### ISSUE TITLE
Strange "Error response from daemon" when starting mysql and tomcat

### ISSUE THREAD

**Issue by csev** [sakaicontrib/docker-sakai-builder#4]
When I follow the instructions, I get a weird message from the startup of mysql and tomcat.   The stranger thing is the message seems not to matter.   Things work.

```
MacBook-Pro-101:docker-sakai-builder csev$ ./sakai-dock.sh mysql
WORK:/Users/csev/dev/docker-sakai-builder/work TOMCAT:/Users/csev/dev/docker-sakai-builder/work/tomcat DEPLOY:/Users/csev/dev/docker-sakai-builder/work/tomcat/deploy WICKET_CONFIG:development
Error response from daemon: No such container: sakai-mysql
b9acee5a6dc90f012e3884f9e33f1f2d4d799f8728e5ea2f724b59eb75f5823c
MacBook-Pro-101:docker-sakai-builder csev$ 

MacBook-Pro-101:docker-sakai-builder csev$ ./sakai-dock.sh tomcat
WORK:/Users/csev/dev/docker-sakai-builder/work TOMCAT:/Users/csev/dev/docker-sakai-builder/work/tomcat DEPLOY:/Users/csev/dev/docker-sakai-builder/work/tomcat/deploy WICKET_CONFIG:development
Error response from daemon: No such container: sakai-tomcat
7a219ae3eaf8d8a273fa04f75d05a2dabad3070c22a330960538dc3590a43207
```

**Comment by jonespm** [comment]
I think I'm lazy here and just call a `docker stop <name>` without checking to see if it's actually running or not (or caring if it was running). I've just been ignoring this message. If it was already running you wouldn't see this message but if not it displays. The idea is that these commands can be quickly runnable to restart the instances.

I could also just possibly  capture and suppress the error message probably like https://stackoverflow.com/a/60291627/3708872 or better check. ;)

**Comment by csev** [comment]
I am getting ready to recommend this to folks so I am stumbling through it :)  A message like 
Shutting down running container (if any)...
Right before the docker stop would suffice.

**Comment by jonespm** [comment]
Sure, I can improve this over the weekend. I'm more concerned about the startup error though but this is no problem to improve.

Prior to these issues I don't think anyone else has looked at this for 3 years, but I've been working with this exclusively locally. So much easier than trying to get Maven/Tomcat/Java/MySQL/etc running correctly nowadays.

**Comment by jonespm** [comment]
I really should also try switching this over to https://hub.docker.com/_/mariadb instead.

**Comment by csev** [comment]
I really like it - my sakai-scripts is nice and seems quicker with compiles and startups than this docker approach - but my approach depends on too much installed the right way on your computer.  Once I get this docker working I can do some side by side comparisons.  I want t be able to do partial builds from various points in the source tree - sometimes without restarting tomcat.  Probably a few new options to the shell script.  Perhap the reason for slow is the use of in-computer NFS.

**Comment by jonespm** [comment]
You can do partial builds with this. The sakai-dock.sh can be run from anywhere in that directory. So you basically would go like

```
cd sakai/basiclti
../../sakai-dock.sh build
```

Sometimes it works but sometimes you have to restart with so `../../sakai-dock.sh tomcat`

Some of the slowness *might* be how much CPU/RAM you're giving Docker. You might also want to check if you have "Use gRPC FUSE for file sharing" checked. I've **felt** that OSX is a little slower than WSL2, but the my other computer with WSL2 might also be faster.

**Comment by csev** [comment]
I did it fresh and clean with all the kill etc - same result.

**Comment by csev** [comment]
I just added the partial build bits to README.md
